server:
  port: 8086

spring:
  application:
    name: auth-service

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:banking_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiration-ms: 86400000 # 24 hours
  issuer: banking-auth-service
