### POST request to example server
POST http://localhost:8081/api/v1/accounts
Content-Type: application/json

{
  "accountHolderName": "Test User",
  "email": "test@example.com",
    "accountType": "SAVINGS",
  "initialDeposit": 1000.00,
  "phone": "1234567890"

}
###