import { useState } from 'react'
import { Link } from 'react-router-dom'
import { createAccount } from '../api/accountApi'
import Notice from '../components/common/Notice'
import StatusBadge from '../components/common/StatusBadge'
import { money } from '../utils/format'

const initial = { accountHolderName: '', phone: '', email: '', accountType: 'SAVINGS', initialDeposit: '' }

export default function CreateAccount() {
  const [form, setForm] = useState(initial); const [account, setAccount] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  async function submit(event) {
    event.preventDefault(); setError(''); setAccount(null)
    if (!form.accountHolderName.trim() || !form.phone.trim() || !form.email.trim() || !form.initialDeposit) return setError('Complete all required fields.')
    if (Number(form.initialDeposit) <= 0) return setError('Initial deposit must be positive.')
    setSaving(true)
    try { setAccount(await createAccount({ ...form, accountHolderName: form.accountHolderName.trim(), phone: form.phone.trim(), email: form.email.trim(), initialDeposit: Number(form.initialDeposit) })) } catch (e) { setError(e.message) } finally { setSaving(false) }
  }
  return <div className="mx-auto max-w-2xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">New account</p><h1 className="mt-1 text-3xl font-bold text-ink">Open an account</h1><p className="mt-2 text-slate-600">Create an account using the Account Service. Your account number is generated by the backend.</p></div>{account ? <section className="panel space-y-5 p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-slate-500">Account created</p><h2 className="mt-1 text-xl font-bold text-ink">{account.accountHolderName}</h2></div><StatusBadge status={account.status} /></div><div className="rounded-xl bg-teal-50 p-4"><p className="text-sm text-teal-800">Your account number</p><p className="mt-1 break-all text-2xl font-bold tracking-wide text-teal-950">{account.accountNumber}</p></div><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Opening balance</dt><dd className="font-semibold text-ink">{money(account.balance)}</dd></div><div><dt className="text-sm text-slate-500">Account type</dt><dd className="font-semibold text-ink">{account.accountType}</dd></div></dl><div className="flex flex-wrap gap-3"><Link className="btn-primary" to={`/?account=${encodeURIComponent(account.accountNumber)}`}>View dashboard</Link><button className="btn-secondary" onClick={() => { setAccount(null); setForm(initial) }}>Create another</button></div></section> : <form className="panel space-y-5 p-5 sm:p-6" onSubmit={submit}>{error && <Notice>{error}</Notice>}<label><span className="field-label">Account holder name</span><input className="field-input" name="accountHolderName" value={form.accountHolderName} onChange={change} required /></label><div className="grid gap-5 sm:grid-cols-2"><label><span className="field-label">Phone number</span><input className="field-input" name="phone" type="tel" value={form.phone} onChange={change} required /></label><label><span className="field-label">Email address</span><input className="field-input" name="email" type="email" value={form.email} onChange={change} required /></label></div><div className="grid gap-5 sm:grid-cols-2"><label><span className="field-label">Account type</span><select className="field-input" name="accountType" value={form.accountType} onChange={change}><option value="SAVINGS">Savings</option><option value="CURRENT">Current</option><option value="FIXED_DEPOSIT">Fixed deposit</option></select></label><label><span className="field-label">Initial deposit (INR)</span><input className="field-input" name="initialDeposit" type="number" min="0.01" step="0.01" value={form.initialDeposit} onChange={change} required /></label></div><div className="flex justify-end"><button className="btn-primary" disabled={saving}>{saving ? 'Creating…' : 'Create account'}</button></div></form>}</div>
}
